# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/titan/jo/WORK/RISC-V/simple_RISC-V.srcs/sources_1/ip/IM/IM.xci
# IP: The module: 'IM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/titan/jo/WORK/RISC-V/simple_RISC-V.srcs/sources_1/ip/IM/IM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/titan/jo/WORK/RISC-V/simple_RISC-V.srcs/sources_1/ip/IM/IM.xci
# IP: The module: 'IM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/titan/jo/WORK/RISC-V/simple_RISC-V.srcs/sources_1/ip/IM/IM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
